# -*- coding: utf-8 -*-
"""EXPLORATORY DATA ANALYSIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PfU6PnCKePmW6J98mKdW-rHovj2v5ime
"""

#IMPORTING LIBRARY

import numpy as np      # datas in a numeric and np is a nick name of numpy
import pandas as pd     # with pandas, data will be in structured format

import matplotlib.pyplot as plt    # used for geographic data
import seaborn as sns              #New version and advanced storafe function

#importing dataset

df = pd.read_csv('/content/diabetes.csv')   #df is a dataframe, csv is a filetype

df         #displaying dataframe/dataset

#EXPLORATORY DATA ANALYSIS

df.head(10)

df.tail(10)

df.shape

df.info()

df.describe()